title: "Jeronimo Ruiz — Robotics & CS"
description: "WPI Robotics + CS | UR10 placement pipeline, Romi robots, wind tunnel project"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
url: "https://jeronimoruiz.github.io"
markdown: kramdown
kramdown:
  input: GFM
social_links:
  github: "https://github.com/jeronimoruiz"
  linkedin: "www.linkedin.com/in/jeronimo-ruiz-fernandez"
